-- TABLE

create table account
(
    id         bigint generated by default as identity,
    username   varchar(255),
    password   varchar(255),
    hash       varchar(255),
    salt       varchar(255),
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    last_login timestamp(6),
    primary key (id)
);

create table users
(
    id               bigint       not null,
    firstname        varchar(255),
    lastname         varchar(255),
    email            varchar(255),
    mobile           varchar(255),
    role             varchar(255),
    avatar           varchar(255),
    email_validated  timestamp(6),
    mobile_validated timestamp(6),
    created_at       timestamp(6) not null,
    updated_at       timestamp(6),
    primary key (id)
);

alter table users
    add constraint fk_users_account foreign key (id) references account (id);

create table category
(
    id          bigint primary key auto_increment,
    parent_id   bigint,
    name        varchar(50),
    description varchar(150),
    created_at  timestamp not null,
    updated_at  timestamp
);

create table review
(
    id         bigint primary key,
    user_id    bigint    not null,
    product_id bigint    not null,
    rating     int,
    comment    varchar(255),
    created_at timestamp not null
);

create table product
(
    id          bigint primary key auto_increment,
    category_id bigint    not null,
    name        varchar(50),
    picture     varchar(150),
    summary     varchar(255),
    description varchar(255),
    price       decimal   not null,
    created_at  timestamp not null,
    updated_at  timestamp
);

alter table category
    add constraint fk_category_category foreign key (parent_id) references category (id);

alter table review
    add constraint fk_review_users foreign key (user_id) references users (id);

alter table review
    add constraint fk_review_product foreign key (product_id) references product (id);

alter table product
    add constraint fk_product_category foreign key (category_id) references category (id);


-- INSERT

insert into account(username, password, created_at)
values ('Azangue', 'kevin.azangue@kubes.com', '2024-02-22T18:13:45'),
       ('Abdul', 'karim.abdul@kubes.com', '2024-02-22T18:13:45'),
       ('Doe', 'john.doe@kubes.com', '2024-02-22T18:13:45');

insert into users(id, firstname, lastname, email, mobile, created_at)
values (1, 'Kevin', 'Azangue', 'kevin.azangue@kubes.com', '01265984521', '2024-02-22T18:13:45'),
       (2, 'Karim', 'Abdul', 'karim.abdul@kubes.com', '023651478952', '2024-02-22T18:13:45'),
       (3, 'John', 'Doe', 'john.doe@kubes.com', '0125874596321', '2024-02-22T18:13:45');

insert into category(name, description, created_at, parent_id)
values ('Fashion', 'for adults and children', '2024-02-22T23:13:45', null),
       ('Clothes', 'for adults and children', '2024-02-22T23:13:45', 1),
       ('Shoes', 'for adults and children', '2024-02-22T23:13:45', 1),
       ('Accessories', 'for adults and children', '2024-02-22T23:13:45', 1),
       ('Jeans', 'for adults and children', '2024-02-22T23:13:45', 2),
       ('Trousers', 'for adults and children', '2024-02-22T23:13:45', 2),
       ('Hoodies & Sweatshirts', 'for adults and children', '2024-02-22T23:13:45', 2),
       ('Cardigans & Sweaters', 'for adults and children', '2024-02-22T23:13:45', 2),
       ('Shirts', 'for adults and children', '2024-02-22T23:13:45',2),
       ('Tennis', 'for adults and children', '2024-02-22T23:13:45',3),
       ('Basketball', 'for adults and children', '2024-02-22T23:13:45',3),
       ('Sneakers', 'for adults and children', '2024-02-22T23:13:45',3);

insert into product(category_id, name, picture, summary, description, price, created_at)
values (1, 'Boss Black', 'Picture', 'Cotton', '100% cotton', 145.85, '2024-02-22T23:13:45')
