name: Build KUMA Spring

env:
  NAME: 'docker-hub'

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    name: Build KUMA Spring
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build
        run: mvn -B package -f pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ZESHADOWZ_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ZESHADOWZ_ACCESS_TOKEN }}

      - name: Dockerize
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: ${{ env.PUSH_TO_HUB }}
          tags: ${{secrets.DOCKER_HUB_ZESHADOWZ_USERNAME }}/kuma-spring-api:$(date +'%Y-%m-%dT%H:%M:%S')
