name: Build KUMA Spring

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    name: Build KUMA Spring
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build
        run: mvn -B package -f pom.xml

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{secrets.DOCKER_HUB_ZESHADOWZ_USERNAME }}/kuma-spring-api:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ZESHADOWZ_USERNAME }}
          password: ${{ secrets.OCKER_HUB_ZESHADOWZ_ACCESS_TOKEN }}

      - name: Push to Docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_ZESHADOWZ_USERNAME }}/kuma-spring-api:latest

